name: SimpleRNGRewards
version: 1.0
main: com.moonlight.simplerngrewards.SimpleRNGRewards
api-version: 1.21
description: A simple plugin that adds the /rngreward command, which gives a reward based on a configurable file.
